#!/usr/bin/env python3
"""Draws the mark from a picture: flat colour blocks, separated only where they need separating.

    python art/make_icon_from_image.py SOURCE.png

**Why from a picture rather than from a composition.** The owner brought a flat, shadowless collage of
bar equipment and asked for the mark to be the whole of it. That is a different request from "draw
something in that style", and the honest way to serve it is to transform the picture he chose rather
than to redraw my impression of it. So this reads his file and computes the drawing.

**Four decisions, all of them his, made in code rather than by hand:**

  * **Every colour is snapped to the application's own palette.** A mark in colours the application
    does not use is a logo wearing somebody else's coat, and it also removes the fourteen thousand
    distinct values the picture carried -- nearly all of them antialiasing between two neighbours --
    which is the property that made the original unusable at small sizes.
  * **Flat: no gradient, no shadow, nothing invented.** What comes out is what went in, quantised.
  * **A separator is drawn only where two blocks would otherwise merge.** This is the correction the
    owner made after seeing the first attempt: it is not "black lines everywhere" but *contrast
    between colour regions* that carries a drawing, and a line between two blocks that already differ
    clearly is ink spent for nothing. So the lines are a consequence of the contrast measurement
    below rather than a layer painted over the top.
  * **The contrast is measured in luminance, not in hue.** Two colours can be far apart in RGB and
    nearly identical to the eye; rose against deep brass is the case in this very palette. Luminance
    is what a small mark is read by, so luminance is what decides.

**Reproducible on purpose.** The output is a function of the source file and the constants below, so
anyone with the picture and this script gets the same SVG. That is the property this project's
provenance rule asks for, and the reason a model-generated image with no parameters is not acceptable
here: an image nobody can reproduce is an image nobody can argue with. The source is copied beside the
generator so that both halves of that sentence hold.

**Small sizes are handled by drawing less, not by scaling down.** Each tier is built at the block
resolution it can afford and enlarged with nearest-neighbour afterwards, so a small tier is a coarser
drawing rather than a shrunken one -- the rule the other two generators already follow.

**On the metadata the source arrived with.** The picture was generated by GPT, and the file came with a
`caBX` chunk: C2PA content credentials, a signature block carrying certificates, a generation record
and whatever else the issuer chose to embed. **It is not carried into this repository.** The rule this
project works by is *declared rather than quietly mixed in*, and a declaration belongs in
`tool/provenance.json`, where a person writes it and a reader can read it -- not as twenty kilobytes of
machine-readable attestation inside an image that ships as an icon. So the source is re-encoded from
its pixels before it is stored, the chunk goes, and the fact stays: **this mark was generated by GPT
and transformed here.** The owner's instruction was exactly that division, name the source and leave
the detail out, and it is written down here because a stripped file with no note would read as an image
of unknown origin, which is a different and worse claim than a plain one.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # pragma: no cover - the message is the point
    raise SystemExit('Pillow is needed, and on this machine it lives on the WSL side')

SIZE = 1024

# ---- the application's own colours, and nothing else ----
GROUND = (0x16, 0x11, 0x0A)
DEEP = (0x6E, 0x55, 0x28)
ROSE = (0xC4, 0x62, 0x6A)
GOLD = (0xE2, 0xA6, 0x3E)
INK = (0xF4, 0xE8, 0xCE)

PALETTE = [GROUND, DEEP, ROSE, GOLD, INK]
HEX = {GROUND: '#16110A', DEEP: '#6E5528', ROSE: '#C4626A', GOLD: '#E2A63E', INK: '#F4E8CE'}

# A pixel in the SOURCE belongs to one of the picture's own black lines when it is this dark and this
# neutral. Judged on the brightest channel rather than on luminance, because the lines are near-black
# while the palette's dark is a warm brown: a luminance test lets the brown through, this does not.
SEPARATOR_LEVEL = 0.22

# ---- the measurement the whole method turns on ----
#
# **How far apart two colours have to be before a line between them is unnecessary.** In luminance,
# from 0 to 1. Below this the two blocks are drawn as one shape and the separator goes in; above it
# the boundary is already visible and no ink is spent. The number is set where it is because of the
# palette's own worst pair: rose and deep brass are far apart in RGB and close to the eye, and a
# threshold that separated them by hue would leave those two blocks fused in the drawing.
#
# Set it to 0.0 and every boundary gets a line -- which is what the first attempt did, and what the
# owner then corrected. Set it to 1.0 and nothing is separated and the drawing is a colour wash.
CONTRAST_FLOOR = 0.20

# ---- the other measurement: what counts as one shape ----
#
# **Distance in RGB within which two neighbouring cells are the same shape.** This is what flattens a
# soft gradient: a ramp of forty steps is forty neighbours all within a few units of each other, so
# they become one region with one colour, which is what the owner asked for. It is deliberately a
# *different* measurement from the contrast floor above, because the two questions are different --
# "is this one shape with modelling in it" against "does the boundary between two shapes need ink".
# Folding them into one number is how the first attempt both flattened real subjects and outlined the
# gradients it had just created.
MERGE_BELOW = 26.0

# **How alike two cells must be before one is allowed to borrow the other's colour.** This is the
# edge-preserving part of flattening the texture: raise it and boundaries start to bleed, lower it and
# the grain survives. It sits below MERGE_BELOW on purpose -- merging two cells into one region is a
# stronger claim than averaging with them, so more is demanded before the average is allowed.
SIMILAR_ENOUGH = 20.0

# How many times the flattening pass runs is a field of each tier below, because it follows the cell
# count rather than the tier's name: a drawing worked out at 48 or 64 cells wants two passes, one at 512
# wants one. It used to be a separate table keyed by name, which stopped meaning anything once the set
# grew from three drawings to nine.

# ---- how much of the drawing each tier can afford ----
#
# `cells` is the block resolution: the drawing is computed at this many cells across and enlarged
# afterwards, so a small tier is a coarser drawing rather than a shrunken one.
#
# **The set exists so that every size a platform asks for renders from whole cells.** An icon is 48 pixels
# on Android's mdpi and 192 on its xxxhdpi, and neither is a multiple of 128: rendering the 128-cell
# drawing at 192 gives 1.5 pixels per cell, and measured against a native 192-cell drawing a quarter of
# the pixels differ and the edges show seams. So there is one drawing per size that needs one, and
# `render_icons.sh` names which to use for each band. `144` is the one size served by a smaller drawing
# than it asks for -- 48 cells at 3x -- because nothing in the set divides it more finely.
#
# **Colours fall as the drawing gets smaller.** Five inks spread over a 48-cell drawing is more ink than
# that many blocks can show as separate regions, and the small tiers of a mark are meant to be a reduction
# of it rather than a recolouring -- the rule the medallion and the A both follow.
TIERS = {
    #          cells  colours  flatten passes
    "full":    dict(cells=512, colors=5, passes=1),   # rendered at 512 and 1024
    "d384":    dict(cells=384, colors=5, passes=1),   # 384
    "d256":    dict(cells=256, colors=5, passes=1),   # 256
    "d192":    dict(cells=192, colors=5, passes=1),   # 192, Android's xxxhdpi
    "d128":    dict(cells=128, colors=5, passes=1),   # 128
    "d96":     dict(cells=96,  colors=5, passes=1),   # 96, Android's xhdpi
    "d72":     dict(cells=72,  colors=5, passes=2),   # 72, Android's hdpi
    "d64":     dict(cells=64,  colors=4, passes=2),   # 64
    "d48":     dict(cells=48,  colors=4, passes=2),   # 48, Android's mdpi
}


def luminance(colour: tuple[int, int, int]) -> float:
    """Relative luminance, the ITU-R BT.709 weights. What the eye sorts a small mark by."""
    return (0.2126 * colour[0] + 0.7152 * colour[1] + 0.0722 * colour[2]) / 255.0


LUM = {colour: luminance(colour) for colour in PALETTE}


def contrast(a: tuple[int, int, int], b: tuple[int, int, int]) -> float:
    return abs(LUM[a] - LUM[b])


def load(source: Path, cells: int) -> "Image.Image":
    """The source, squared, and reduced to the tier's block resolution in one step.

    **Reduced before anything is decided, rather than after.** Deciding at 1024 and then shrinking
    means the decisions were made about detail the tier cannot show: islands of a dozen colours that
    average into a speckle nobody asked for. Deciding at the tier's own resolution is both more honest
    and much faster, since the per-pixel work happens once, at the size that ships.
    """
    image = Image.open(source)
    if image.mode in ('RGBA', 'LA', 'P'):
        image = image.convert('RGBA')
        flat = Image.new('RGBA', image.size, GROUND + (255,))
        flat.alpha_composite(image)
        image = flat
    image = image.convert('RGB')
    side = min(image.size)
    left = (image.width - side) // 2
    top = (image.height - side) // 2
    image = image.crop((left, top, left + side, top + side))
    # BOX averages each cell, which is what a photograph wants: the average of a region is a better
    # statement about it than one sampled pixel.
    return image.resize((cells, cells), Image.BOX)


def snap(pixel: tuple[int, int, int], keep: list[tuple[int, int, int]]) -> tuple[int, int, int]:
    """The nearest colour in the palette, by squared distance in RGB."""
    best, best_distance = keep[0], None
    for candidate in keep:
        distance = sum((a - b) ** 2 for a, b in zip(pixel, candidate))
        if best_distance is None or distance < best_distance:
            best, best_distance = candidate, distance
    return best


def source_palette(source: "Image.Image", count: int) -> list[tuple[int, int, int]]:
    """The picture's own dominant colours, by median cut.

    **This replaced a palette of the application's six, and the render is why.** Snapping a photograph
    of warm browns onto a palette whose four dark values are all near-black collapsed almost every
    block into the ground; the contrast rule then found no contrast anywhere, declared a boundary
    everywhere, and returned a black square with a few bright specks in it. Which is the correct
    behaviour of the rule and the wrong palette to feed it. **The picture's own colour regions are the
    drawing** -- the application's palette supplies the ground and the separators, which is exactly
    the part the picture already had in black.
    """
    sample = source.resize((192, 192), Image.BOX)
    cut = sample.quantize(colors=count, method=Image.MEDIANCUT)
    raw = cut.getpalette()[: count * 3]
    counts = sorted(cut.getcolors(), reverse=True)
    present = [index for _n, index in counts]
    colours = []
    for index in present:
        colours.append((raw[index * 3], raw[index * 3 + 1], raw[index * 3 + 2]))
    return colours


def flatten_texture(source: "Image.Image", cells: int, strength: int) -> "Image.Image":
    """Unifies modelling inside a shape without touching the boundaries between shapes.

    **This is the "a soft gradient becomes one colour" instruction, and it cannot be a blur.** A
    Gaussian blur averages across boundaries as happily as within them, so two subjects that meet would
    bleed into each other -- which is the other instruction, and the two would cancel out. So the
    smoothing is conditional: a cell moves toward the average of its neighbours **only if it is already
    close to them**, and a cell on a boundary finds most of its neighbours unlike itself and is left
    where it is.

    The picture this runs on is a painting with paper grain in it, and that grain is what a quantiser
    turns into speckle: measured, the local deviation from a smooth version is about sixteen parts in
    two hundred and fifty-five, which is texture rather than structure. Removing it before the colours
    are decided is what makes the drawing read as blocks instead of as noise.
    """
    rgb = source.copy()
    pixels = rgb.load()
    for _ in range(strength):
        source_pixels = rgb.copy().load()
        for y in range(cells):
            for x in range(cells):
                here = source_pixels[x, y]
                near = [here]
                for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
                    if 0 <= nx < cells and 0 <= ny < cells:
                        other = source_pixels[nx, ny]
                        if sum((a - b) ** 2 for a, b in zip(here, other)) <= SIMILAR_ENOUGH ** 2:
                            near.append(other)
                if len(near) > 1:
                    pixels[x, y] = tuple(sum(c[i] for c in near) // len(near) for i in range(3))
    return rgb


def build_regions(source: "Image.Image", palette, cells: int, merge_below: float):
    """Groups adjacent cells whose colours are close into regions, and gives each one colour.

    **This is where both of the owner's corrections are answered, and they are two sides of it.**

      * **A soft gradient is one region, not many.** A gradient is variation *inside* a shape, and the
        owner asked for such a block to become a single flat colour. So neighbouring cells merge when
        their source colours are close, and a ramp of forty steps collapses into one region instead of
        forty bands that a small mark would show as noise.
      * **Two subjects that look alike still do not merge.** Regions are built from the *source*
        colours, not from the palette: two blocks whose palette colours happen to be near-identical
        are still two regions if the picture drew them as two, and every region boundary is then
        eligible for a separator. Merging by palette index instead would fuse exactly the pair the
        owner warned about.

    `merge_below` is the colour distance within which two neighbouring cells count as one shape. It is
    a distance in RGB, and it is the one number that decides how much of the picture's modelling
    survives as blocks; it does not decide anything about boundaries, which is what makes the two
    corrections independent.
    """
    pixels = source.load()
    parent = list(range(cells * cells))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[max(ra, rb)] = min(ra, rb)

    def close(a, b) -> bool:
        return sum((p - q) ** 2 for p, q in zip(a, b)) <= merge_below ** 2

    for y in range(cells):
        for x in range(cells):
            index = y * cells + x
            here = pixels[x, y]
            if x + 1 < cells and close(here, pixels[x + 1, y]):
                union(index, index + 1)
            if y + 1 < cells and close(here, pixels[x, y + 1]):
                union(index, index + cells)

    members: dict[int, list[int]] = {}
    for index in range(cells * cells):
        members.setdefault(find(index), []).append(index)

    flat = [[None] * cells for _ in range(cells)]
    for root, cells_of_region in members.items():
        total = [0, 0, 0]
        for index in cells_of_region:
            px, py = index % cells, index // cells
            colour = pixels[px, py]
            total[0] += colour[0]
            total[1] += colour[1]
            total[2] += colour[2]
        mean = tuple(value // len(cells_of_region) for value in total)
        # The region's one colour is the nearest of the picture's own dominant colours, so a flattened
        # gradient lands on a colour that exists in the picture rather than on an average of it.
        chosen = snap(mean, palette)
        for index in cells_of_region:
            flat[index // cells][index % cells] = chosen
    return flat


def quantise(source: "Image.Image", palette, cells: int):
    """The source's colours, the source's lines, then a separator only where one is needed.

    Two things the owner asked for are done in order here: adjacent cells of the same colour are one
    region, so a gradient is flat; and every boundary between two *different* regions is measured, so
    two subjects that merely look alike still get their line.
    """
    luminances = dict(LUM)
    luminances[GROUND] = luminance(GROUND)
    for colour in palette:
        luminances[colour] = luminance(colour)

    grid = build_regions(source, palette, cells, MERGE_BELOW)
    pixels = source.load()
    for y in range(cells):
        for x in range(cells):
            pixel = pixels[x, y]
            if max(pixel) / 255.0 < SEPARATOR_LEVEL and (max(pixel) - min(pixel)) < 60:
                grid[y][x] = GROUND

    # Where a boundary needs ink it goes into the second of the two cells: writing it into the first
    # would let the next comparison read the line as that cell's colour and undo it, since every cell
    # is compared from two sides.
    lines = [[False] * cells for _ in range(cells)]
    for y in range(cells):
        for x in range(cells):
            here = grid[y][x]
            if here == GROUND:
                continue
            for nx, ny in ((x + 1, y), (x, y + 1)):
                if nx >= cells or ny >= cells:
                    continue
                there = grid[ny][nx]
                if there == GROUND or there == here:
                    continue
                if abs(luminances[here] - luminances[there]) < CONTRAST_FLOOR:
                    lines[ny][nx] = True
    for y in range(cells):
        for x in range(cells):
            if lines[y][x]:
                grid[y][x] = GROUND
    return grid


def to_svg(grid, cells: int, tier: str, spec: dict, hexes: dict) -> str:
    """One rectangle per horizontal run of one colour, in cell units, scaled by the viewBox.

    Runs rather than a path per region: the ground rectangle covers the canvas and every other colour
    is painted over it, so a run of ground inside the drawing is simply not emitted. The file is then
    proportional to the number of boundaries rather than to the number of cells.

    `shape-rendering="crispEdges"` is what makes a cell grid read as blocks instead of as a blur: the
    default smooths neighbouring rectangles into each other, which reintroduces exactly the gradients
    this drawing exists to remove.
    """
    unit = SIZE / cells
    pieces = [f'  <rect x="0" y="0" width="{SIZE}" height="{SIZE}" fill="{hexes[GROUND]}"/>']
    for y in range(cells):
        x = 0
        while x < cells:
            colour = grid[y][x]
            start = x
            while x < cells and grid[y][x] == colour:
                x += 1
            if colour != GROUND:
                pieces.append(
                    f'  <rect x="{round(start * unit, 2)}" y="{round(y * unit, 2)}" '
                    f'width="{round((x - start) * unit, 2)}" height="{round(unit, 2)}" '
                    f'fill="{hexes[colour]}"/>'
                )
    body = "\n".join(pieces)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" width="{SIZE}" height="{SIZE}" shape-rendering="crispEdges">
  <!--
    Hollow Court's mark, drawn from the owner's picture. Every block flattened; the colours are the
    picture's own dominant ones, and the separators and the ground are the application's near-black.
    A separator is drawn only where two neighbouring regions were too close in luminance to read as
    two, so no ink is spent on a boundary that was already visible. Generated by
    art/make_icon_from_image.py, so edit that and re-run rather than editing this. Tier: {tier},
    worked out at {cells} cells across, {spec["colors"]} of the picture's colours, contrast floor
    {CONTRAST_FLOOR}.
  -->
{body}
</svg>
"""


def main(argv: list[str]) -> int:
    here = Path(__file__).parent
    kept = here / 'mark-source.png'

    if argv:
        source = Path(argv[0])
        if not source.is_file():
            print(f'no such source: {source}', file=sys.stderr)
            return 2
        kept.write_bytes(source.read_bytes())
        print(f'kept the source as {kept.name} ({kept.stat().st_size} bytes)')
    else:
        # **No argument means "redraw from the source already in the repository".** `render_icons.sh`
        # calls this with no arguments, because its work is to redraw whatever the mark currently is,
        # and making it pass a path would put the knowledge of where a picture lives in the wrong file.
        source = kept
        if not source.is_file():
            print(f'no source given, and none kept at {source}', file=sys.stderr)
            print(f'  usage: python {Path(__file__).name} SOURCE.png', file=sys.stderr)
            return 2
        print(f'redrawing from the kept source ({source.stat().st_size} bytes)')

    # The picture's own colours are taken once, at the widest count any tier needs, so that the tiers
    # differ in how much detail they keep rather than in which image they are drawing.
    widest = max(spec['colors'] for spec in TIERS.values())
    palette = source_palette(load(source, 512), widest)
    print('the picture\'s colours: ' + ', '.join('#%02X%02X%02X' % c for c in palette))

    for tier, spec in TIERS.items():
        cells = spec['cells']
        # Each tier keeps the most separated of those colours, by luminance: the small tier is a
        # reduction of the same drawing, and the colours it drops are the ones closest to their
        # neighbours, which are also the ones it could not have shown separately anyway.
        keep = sorted(palette, key=luminance, reverse=True)[: spec['colors']]
        keep = sorted(keep, key=luminance)
        hexes = {GROUND: HEX[GROUND]}
        for colour in keep:
            hexes[colour] = '#%02X%02X%02X' % colour

        base = load(source, cells)
        base = flatten_texture(base, cells, spec['passes'])
        grid = quantise(base, keep, cells)
        used = sorted({c for row in grid for c in row}, key=luminance)
        # The file name follows the tier's own name, so a drawing is findable from the size it serves:
        # `d192` is the one to render 192 pixels from, and `render_icons.sh` names it there.
        name = 'icon-hc-image.svg' if tier == 'full' else f'icon-hc-image-{tier[1:]}.svg'
        svg = to_svg(grid, cells, tier, spec, hexes)
        (here / name).write_text(svg, encoding='utf-8', newline='\n')
        print(f'  wrote {name} ({tier}: {cells} cells, {len(svg)} bytes, '
              f'inks used: ' + ', '.join(hexes[c] for c in used) + ')')

    print('now render it and look at it: MARK=image bash art/render_icons.sh')
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
